@startuml
title fonctionnement d'une camera

participant "mg : moteurGraphique" as mg
participant "jeu : Jeu" as jeu
participant "cam : Cam" as cam
participant "e : Entite" as e


 
activate mg
    activate jeu
    create cam
        jeu -> cam: Camera(Entite e)
        activate cam

            cam -> e : getPos()
            cam <-- e : pos
        deactivate cam

        mg -> jeu : evoluer()
        jeu -> cam : deplacer(e2)
        activate cam
            cam -> e : getPos()
            cam <-- e : pos
            jeu <-- cam

        deactivate cam
        mg <-- jeu
    deactivate jeu
deactivate mg
@enduml