@startuml
title implementation collision mur
participant "mg: MoteurGraphique" as moteurJeu
participant "dj: DessinJeu" as dessinJeu
participant "j: Jeu" as jeu
participant "joueur: Aventurier" as joueur
participant "gui:InterfaceGraphique" as gui
participant "controleur:Controleur" as controleur
participant "carte: Labyrinthe" as carte

    loop [non etreFini]
        moteurJeu -> jeu : etreFini
        activate jeu
        moteurJeu <-- jeu
        deactivate jeu
        moteurJeu -> gui : getControleur()
        activate gui
        moteurJeu <-- gui : controleur
        deactivate gui
        moteurJeu -> controleur : getCommande()
        activate controleur
        moteurJeu <-- controleur : commande
        deactivate controleur
        moteurJeu -> jeu : evoluer(commande)
        activate jeu
        jeu -> joueur : deplacer(commande)
        activate joueur
        joueur -> carte : getCaseAtVec2(position)
        activate carte
        joueur <-- carte : case
        deactivate carte
        alt case.isTraversable()
            alt commande.gauche
                joueur -> joueur : x-1
            end
            alt commande.Droite 
                joueur -> joueur : x+1
            end
            alt commande.haut
                joueur -> joueur : y-1
            end
            alt commande.bas
                joueur -> joueur : y+1
            end
        end
        jeu <-- joueur
        deactivate joueur
        moteurJeu <-- jeu
        deactivate jeu
        moteurJeu -> dessinJeu : dessiner
        activate dessinJeu
        moteurJeu <-- dessinJeu
        deactivate dessinJeu
    end

@enduml