@startuml
title création et action du gobelin

participant "gob: Gobelin" as gob
participant "joueur: Aventurier" as joueur
participant "m: Monstre" as m

[-> gob : new
activate  gob
    gob -> joueur : attaquer(int x)
    activate joueur
        joueur -> joueur : subirDegats(x)
        joueur --> gob 
    deactivate joueur
    gob -> m : soigner(int s, m)
    activate m
        m -> m : seSoigner(s)
        m --> gob
    deactivate m
    gob -> gob : subirDegats(int z)
    gob -> gob : seSoigner(int y)
    gob -> gob : etreMort()
    activate  gob
        gob --> gob : boolean
    deactivate gob    
[<- gob
deactivate gob
@enduml